language: node_js

node_js: stable

services:
  - mongodb

cache:
  timeout: 1000
  directories:
    - $HOME/.npm-cache
    - $HOME/.npm-prefix
    - $HOME/.npm

install:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - npm install -g codecov
  - cd react-blog
  - npm install
  - cd ../node-blog-api
  - npm install
  - cd ../react-admin
  - npm install
  - cd ../react-music-app
  - npm install

before_script:
  - sleep 15

script:
  - set -e
  - cd $TRAVIS_BUILD_DIR/react-blog
  - NODE_OPTIONS=--max_old_space_size=1024 CI=false npm run build
  - cd ../node-blog-api
  - npm run test:cov
  - codecov
  - cd ../react-admin
  - CI=false npm run build
  - cd ../react-music-app
  - CI=false npm run build

branches:
  only:
    - master