language: node_js

node_js:
  - "10.16.0"

services:
  - mongodb
  - docker

cache:
  timeout: 1000
  directories:
    - $HOME/.npm-cache
    - $HOME/.npm-prefix
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - env: server
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/server
        - npm install
      script:
        - npm run test:cov
        - codecov
        - npm run build
    - env: web
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/web
        - npm install
      script:
        - NODE_OPTIONS=--max_old_space_size=1024 CI=false npm run build
    - env: admin
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/admin
        - npm install
      script:
        - CI=false npm run build

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
    branch: master
on:
  branch: master