version: '3.4'
services:
  server:
    build: ./node-server
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ./nginx/static/upload:/code/upload
    command: npm run start
  ssr:
    build: ./react-blog
    depends_on:
      - server
    command: npm run start
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/logs:/var/log/nginx
      - ./nginx/static:/etc/nginx/static
  db:
    image: mongo:3.2
    volumes:
      - ../data/mongo-db:/data/db