version: '3'
services:
  api:
    build: ./server
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start:prod
  web:
    build: ./web
    command: npm run start:prod
  admin:
    build: ./admin
    command: npm run start:prod
  nginx:
    build: ./nginx
    depends_on:
      - server
      - web
      - admin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/logs:/var/log/nginx
      - ./nginx/certificate:/etc/nginx/certificate
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-backup:/data/mongo-backup
      - ../data/mongo-db:/data/db
    ports:
      - 27017:27017