version: '3'
services:
  node:
    build: .
    command: "npm run start"
    ports:
      - "80:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  db:
    image: mongo:3.2