version: '3'
services:
  node:
    build: .
    command: "pm2 start ./server/app.js"
    ports:
      - "80:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mongo:3.2