version: '3.4'
services:
  api:
    build: ./node-blog-api
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start:prod
  blog:
    build: ./react-blog
    command: npm run start:prod
  admin:
    build: ./react-admin
    command: npm run start:prod
  music:
    build: ./react-music-app
    command: npm run start:prod
  nginx:
    build: ./nginx
    depends_on:
      - api
      - blog
      - admin
      - music
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/logs:/var/log/nginx
      - ./nginx/certificate:/etc/nginx/certificate
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-backup:/data/mongo-backup
      - ../data/mongo-db:/data/db
    ports:
      - 27017:27017