version: '3.4'
services:
  api:
    build: https://gitee.com/chengli01/node-blog.git
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start
    ports:
      - 8080:8080
    network_mode: "host"
  blog:
    build: https://gitee.com/chengli01/react-blog.git
    command: "npm run start:prod"
    ports:
      - 3000:3000
    network_mode: "host"
  admin:
    build: https://gitee.com/chengli01/react-blog-admin.git
    command: npm run start
    ports:
      - 3002:3002
    network_mode: "host"
  nginx:
    build: https://gitee.com/chengli01/blog-nginx.git
    network_mode: "host"
    depends_on:
      - api
      - blog
      - admin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/logs:/var/log/nginx
      - ../blog-nginx/certificate:/etc/nginx/certificate
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-db:/data/db
    ports:
      - 27017:27017