version: '3.4'
services:
  server:
    build: ../blog-server
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start:prod
  web:
    build: ../blog-web
    command: npm run start:prod
  admin:
    build: ../blog-admin
    command: npm run start:prod
  music:
    build: ../blog-music-app
    command: npm run start:prod
  nginx:
    build: ../blog-nginx
    depends_on:
      - server
      - web
      - admin
      - music
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/logs:/var/log/nginx
      - ./nginx/certificate:/etc/nginx/certificate
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-backup:/data/mongo-backup
      - ../data/mongo-db:/data/db
    ports:
      - 27017:27017