version: '3'
services:
  node:
    build: .
    volumes:
      - "./static/upload:/code/static/upload"
    command: "npm run start"
    ports:
      - "443:443"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mongo:3.2
    volumes:
      - "/data/db:/data/db"