version: '3'
services:
  server:
    image: bs32g1038/node-blog-server:v2
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start:prod --MONGODB_HOSTNAME=db
    environment:
      - MONGODB_URL=mongodb://db:27017/blog
  web:
    image: bs32g1038/node-blog-web:v2
    command: DOMAIN=https://www.lizc.net npm run start:prod
  admin:
    image: bs32g1038/node-blog-admin:v2
    command: npm run start:prod
  nginx:
    image: bs32g1038/node-blog-nginx:v2
    depends_on:
      - server
      - web
      - admin
    ports:
      - 80:80
      - 443:443
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-backup:/data/mongo-backup
      - ../data/mongo-db:/data/db