version: '3'
services:
  node:
    build: .
    volumes:
      - "./static/images:/code/static/images"
    command: "npm run start"
    ports:
      - "80:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mongo:3.2