version: '3'
services:
  node:
    build: .
    volumes:
      - "./static/upload:/code/static/upload"
    command: "npm run start"
    ports:
      - "443:443"
      - "80:80"      
    depends_on:
      - db
      - nginx
    stdin_open: true
    tty: true
  db:
    image: mongo:3.2
    volumes:
      - "./mongo-db:/data/db"
  nginx:
    restart: always
    image: nginx:1.12-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs:/var/log/nginx
      - ./static:/etc/nginx/static
      - ./nginx/certificate:/etc/nginx/certificate
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf