version: '3.4'
services:
  server:
    image: lcnotes/blog-server:v2.0.0
    depends_on:
      - db
    volumes:
      - ../data/logs:/code/logs
      - ../data/blog/upload:/code/static/upload
    command: npm run start:prod
  web:
    image: lcnotes/blog-web:v2.1.1
    command: npm run start:prod
  admin:
    image: lcnotes/blog-admin:v2.0.0
    command: npm run start:prod
  music:
    image: lcnotes/blog-music-app:v2.0.0
    command: npm run start:prod
  nginx:
    image: lcnotes/blog-nginx:v2.1.0
    depends_on:
      - server
      - web
      - admin
      - music
    ports:
      - 80:80
      - 443:443
  db:
    image: mongo:4.1
    volumes:
      - ../data/mongo-backup:/data/mongo-backup
      - ../data/mongo-db:/data/db
    ports:
      - 27017:27017